node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '8f632d3f-220a-45fd-9cab-6497f3327c2d') {
       def app = docker.build("yoavj/jen:${commit_id}", '.').push()
       def app2 = docker.build("yoavj/jen:latest", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 yoavj/jen:latest
      docker kill docker_test
      
      '''
     }
   }

